//
//  User.swift
//  MySampleApp
//
//
// Copyright 2018 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
//
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to 
// copy, distribute and modify it.
//
// Source code generated from template: aws-my-sample-app-ios-swift v0.21
//

import Foundation
import UIKit
import AWSDynamoDB
import AWSAuthCore

@objcMembers
class User: AWSDynamoDBObjectModel, AWSDynamoDBModeling {
    
    var _userId: String?
    var _biceps: NSNumber?
    var _calves: NSNumber?
    var _chest: NSNumber?
    var _dOB: String?
    var _firstName: String?
    var _forearms: NSNumber?
    var _height: String?
    var _hips: NSNumber?
    var _lastName: String?
    var _location: String?
    var _neck: NSNumber?
    var _thighs: NSNumber?
    var _trainerEmail: String?
    var _units: String?
    var _waist: NSNumber?
    var _weight: NSNumber?
    var _wrist: NSNumber?
    
    class func dynamoDBTableName() -> String {

        return "sportsapple-mobilehub-1970899121-User"
    }
    
    class func hashKeyAttribute() -> String {

        return "_userId"
    }
    
    override class func jsonKeyPathsByPropertyKey() -> [AnyHashable: Any] {
        return [
               "_userId" : "userId",
               "_biceps" : "Biceps",
               "_calves" : "Calves",
               "_chest" : "Chest",
               "_dOB" : "DOB",
               "_firstName" : "First Name",
               "_forearms" : "Forearms",
               "_height" : "Height",
               "_hips" : "Hips",
               "_lastName" : "Last Name",
               "_location" : "Location",
               "_neck" : "Neck",
               "_thighs" : "Thighs",
               "_trainerEmail" : "Trainer Email",
               "_units" : "Units",
               "_waist" : "Waist",
               "_weight" : "Weight",
               "_wrist" : "Wrist",
        ]
    }
    
    func createUser(userId: String) {
        let dynamoDbObjectMapper = AWSDynamoDBObjectMapper.default()
        
        // Create data object using data models you downloaded from Mobile Hub
        let userItem: User = User()
        userItem._userId = userId
        userItem._firstName = "HBA"
        userItem._lastName = "Freelance"
        userItem._trainerEmail = "none"
        userItem._biceps = 31
        userItem._calves = 32
        userItem._chest = 33
        userItem._dOB = "15-03-1976"
        userItem._forearms = 34
        userItem._height = "6'0''"
        userItem._hips = 35
        userItem._location = "Gym"
        userItem._neck = 36
        userItem._thighs = 37
        userItem._units = "Imperial"
        userItem._waist = 38
        userItem._weight = 39
        userItem._wrist = 40
        //Save a new item
        dynamoDbObjectMapper.save(userItem, completionHandler: {
            (error: Error?) -> Void in
            
            if let error = error {
                print("Amazon DynamoDB Save Error: \(error)")
                return
            }
            print("An item was saved.")
        })
    }
}
